### ISSUE TITLE
Answer highlighting absent

### ISSUE THREAD

**Issue by cgaaf** [aliemteam/ALiEMU#144]
Correct and Incorrect answer highlighting is absent. Not sure if this is a result of some of the recent changes. As long as the answer explanation provides the correct feedback this shouldn't be a big problem. We could potentially wait and see how it is received before pursuing a fix. 

![answer highlighting](https://user-images.githubusercontent.com/11409288/27797429-97ea2c14-5fdb-11e7-9e6e-cd1e1fe472b4.PNG)

**Comment by dsifford** [comment]
This was on purpose. If we leave the highlighting which shows the correct answer when the wrong one is selected, then the quizzes can be too easily pencil whipped.
