### ISSUE TITLE
Activate module button missing

### ISSUE THREAD

**Issue by cgaaf** [aliemteam/ALiEMU#145]
There used to be an activate module button displayed so a user could actually sign up to complete a module. This button is now missing so LearnDash won't log credit. This needs an urgent fix. I've taken a screen shot and provided a blue circle where the button used to be. I think maybe this is a css bug? Maybe it's just not being rendered properly? Trying to look through chrome's dev tools to see if it's hidden.

![start module button missing](https://user-images.githubusercontent.com/11409288/27797729-ac513c1e-5fdc-11e7-988c-d29e161f4572.PNG)

**Comment by cgaaf** [comment]
@dsifford I think maybe this occurred after the recent changes? I expect we'll be getting a lot of emails about dashboard functionality not working soon

**Comment by cgaaf** [comment]
Hmm actually it seems when I go to the same page in incognito mode it's there. Maybe it's just my account? Will continue to troubleshoot. I have a shift today so I may be interrupted if anyone has the time to check on their own accounts. 

![incognito mode](https://user-images.githubusercontent.com/11409288/27797830-0a55c9ec-5fdd-11e7-91a9-a64b04b8fb7d.PNG)

**Comment by cgaaf** [comment]
This actually may be a non issue. Will keep this open for now while I make sure that everything is in order.

**Comment by dsifford** [comment]
Reopen this if anything comes up. Closing for now.
