### ISSUE TITLE
No quiz feedback after completion

### ISSUE THREAD

**Issue by cgaaf** [aliemteam/ALiEMU#146]
I'm noticing that after a quiz is completed there is no feedback regarding pass/failure. Example screenshot is below after completion of a quiz. I'll continue to troubleshoot. Leaving this open for now. 

![nofeedback](https://user-images.githubusercontent.com/11409288/27798054-dbc14128-5fdd-11e7-922c-afe6e1873c2f.PNG)

**Comment by dsifford** [comment]
Was this working prior to the changes I made? I've never seen feedback after a quiz and I wasn't aware we were collecting it or how we were doing it.

**Comment by dsifford** [comment]
Any updates on this @Cgaafary ?

**Comment by dsifford** [comment]
No response. Closing.
