### ISSUE TITLE
Home page links wrong

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#160]
On the mobile view iPhone SE, all 3 module icons direct to AIR Series URL on ALiEMU. Please fix

**Comment by michellealiem** [comment]
![img_0989](https://user-images.githubusercontent.com/15097022/30780564-8a22d8b0-a0c2-11e7-9c0f-413a69ee564b.PNG)

**Comment by dsifford** [comment]
Can we confirm that this is only on iphone on safari? I can't reproduce this.
