### ISSUE TITLE
Gray foot bar in the way

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#161]
On mobile iPhone SE, the gray footer floats in the middle of screen while scrolling to see all the Capsules modules

**Comment by michellealiem** [comment]
![img_0988](https://user-images.githubusercontent.com/15097022/30780573-d72d0568-a0c2-11e7-8407-eceb2d51a35e.PNG)

**Comment by dsifford** [comment]
What browser is this?

**Comment by michellealiem** [comment]
iPhone safari

**Comment by dsifford** [comment]
Figured that was the case... IE and Safari both have separate competing quirks when it comes to flexbox layout.

I'll see if I can fix tomorrow.

**Comment by dsifford** [comment]
In the meantime, chrome mobile should still work... ~~Safari~~

**Comment by jbronner1** [comment]
Dang, @michellealiem beat me to this! I'm trying hard to run the github train... Here's the ipad screenshot from the commenter:

![image](https://user-images.githubusercontent.com/17776976/30821223-91bb7d26-a1f2-11e7-83ea-857432f4d163.png)

**Comment by dsifford** [comment]
Fixed in 3946347
