### ISSUE TITLE
Need space on restart of quizzes on Capsules after failed attempt.

### ISSUE THREAD

**Issue by jbronner1** [aliemteam/ALiEMU#166]
Needs space after "Start Quiz" button

![image](https://user-images.githubusercontent.com/17776976/30918598-076a4298-a36d-11e7-8402-da48d057c46f.png)

**Comment by dsifford** [comment]
@jbronner1 Can you please also include a direct URL to the page in your issues next time?

Greatly appreciate it!

**Comment by dsifford** [comment]
Can't reproduce this.

**Comment by dsifford** [comment]
Can't reproduce this.
