### ISSUE TITLE
Warped image dimensions on mobile view

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#183]
Dimensions of images look warped on mobile but ok on desktop

![aliemu mobile image](https://user-images.githubusercontent.com/15097022/34660900-bfbf7fec-f3fa-11e7-9a49-fe23c928a29e.jpeg)

<img width="1070" alt="aliemu desktop image" src="https://user-images.githubusercontent.com/15097022/34660922-e4122b42-f3fa-11e7-99e3-41d2fb6d06c0.png">

**Comment by dsifford** [comment]
The height of this image is hard-set.. That's the reason for the distortion.
