### ISSUE TITLE
Course navigation widget

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#185]
Can we activate this please sooner than later? Realizing how hard it is to find a Module home page again once you are within the lesson or topic. Instead have to go all the way back to the home page and go through several dropdown menus or clicks.

https://www.aliemu.com/wp-admin/widgets.php

![screenshot 2018-01-07 08 59 25](https://user-images.githubusercontent.com/15097022/34661644-e75a4596-f3ff-11e7-8f7f-bcdae3e80e02.png)

**Comment by michellealiem** [comment]
Let's activate this! Will be super helpful. Thanks.

**Comment by dsifford** [comment]
As I said yesterday. There are things blocking activation of this right now that need to be finished first

**Comment by michellealiem** [comment]
Ah totally forgot. Lost track - thanks
