### ISSUE TITLE
New series launch: ITE Questions 

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#187]
1. Add new icon on home page (4th one alongside AIR, Pro, Cap)
2. Add "ALiEM In Training Exam Prep" in the top SERIES dropdown menu 
3. Create SVG version of logo for home page (actually create logo first!)

**Comment by michellealiem** [comment]
Book cover - can we use somehow and convert to a logo? Alternatively, if wanna go simpler, can use ALiEM logo and add text "ALiEM In Training Exam Prep"
![ite book cover](https://user-images.githubusercontent.com/15097022/34687587-0f0d75f4-f464-11e7-82d7-2b7546a94d98.png)

**Comment by dsifford** [comment]
I think we should probably re-think the homepage design because the icon way won't scale to many more courses.

Maybe you could scout out some nice design inspiration for this?

**Comment by michellealiem** [comment]
Will do! For the short term, if we can manage to launch this in the next
1-2 weeks, can we just add the logo icon? Either way, am already planning
on figuring a course grid design. It won’t be anything too fancy but
hopefully will be user friendly and scalable.


On January 8, 2018 at 11:14:28 AM, Derek Sifford (notifications@github.com)
wrote:

I think we should probably re-think the homepage design because the icon
way won't scale to many more courses.

Maybe you could scout out some nice design inspiration for this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aliemteam/ALiEMU/issues/187#issuecomment-356066241>,
or mute
the thread

**Comment by dsifford** [comment]
Sure thing
