### ISSUE TITLE
Add Editor names in ITE Prep course home page

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#188]
https://www.aliemu.com/in-training-exam/

* **Editors:** Michael Gottlieb, MD; Rochelle Zarzar, MD; Philippe Bierny, BA
* **Associate Editors:** Dorothy Habrat, DO; Margaret Sheehy, MD, MSc; Samuel Zidovetzki, MD; Adaira Chou, MD, MEd (c); Nikita Joshi, MD; Michelle Lin, MD
* **iBook Citation:** Gottlieb M, Zarzar R, Bierny P, eds. ALiEM In-Training Exam Prep: Emergency Medicine (Question Sets #1-5), 2nd edition. San Francisco: ALiEM Publishing, 2016. ISBN 978-0-9907948-8-2

**Comment by dsifford** [comment]
@michellealiem What citation style is that for the iBook citation? Should that be AMA format like the rest of the site?

**Comment by michellealiem** [comment]
Yes please! AMA would be great. Feel free to tweak.


On January 13, 2018 at 5:05:35 PM, Derek Sifford (notifications@github.com)
wrote:

@michellealiem <https://github.com/michellealiem> What citation style is
that for the iBook citation? Should that be AMA format like the rest of the
site?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aliemteam/ALiEMU/issues/188#issuecomment-357480413>,
or mute
the thread
