### ISSUE TITLE
Quiz prerequisite feature broken

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#191]
Originally I had set the ITE Prep Course such that you have to pass Set 1 to unlock Sets 2-5. Instead it required me to finish all sets in sequential order to unlock the next set. 

Example: When I clicked on set 5, it took me to the set 4 page, which then sent me to the set 3 page, then set 2. Then it took me to set 1 which I had to complete first.

So I deactivated this option for now until we can figure out how to fix.

<img width="802" alt="screenshot 2018-01-11 11 44 15" src="https://user-images.githubusercontent.com/15097022/34844081-25e6515c-f6c5-11e7-8749-31f15ddb86c4.png">

**Comment by michellealiem** [comment]
AHA! Eureka. Figured out. You have to put all quizzes within the same Lesson block to use this feature. I had put 1 quiz per lesson earlier.

**Comment by dsifford** [comment]
Ask @Cgaafary or @jbronner1 about this. This is out of my wheelhouse
