### ISSUE TITLE
Image does not center-align

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#194]
Despite clicking on the CENTER button for the image, it still remains LEFT-aligned. I had to go into HTML and wrap the image with <center> code. Weird, right? Can we re-enable this button?

URL: https://www.aliemu.com/wp-admin/post.php?post=5267&action=edit

![screenshot 2018-01-16 16 57 55](https://user-images.githubusercontent.com/15097022/35019978-a27bd742-fade-11e7-82c2-ac3ff962a38e.png)

![screenshot 2018-01-16 16 58 01](https://user-images.githubusercontent.com/15097022/35019981-a472864a-fade-11e7-84bc-17bc5d72822e.png)

**Comment by dsifford** [comment]
Most likely related to #193
