### ISSUE TITLE
Move ITE Prep comments to dedicated Slack channel

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#195]
Can we create an automated process whereby questions for the ITE Course get posted in the #ite (not yet created) channel on ALiEM Innovation Lab account? Similar to AIR and Capsules comments?

**Comment by dsifford** [comment]
Yep, shouldn't be a problem. 

Let me know when the channel gets created.

**Comment by michellealiem** [comment]
Channel is created! #ite-prep

**Comment by dsifford** [comment]
Gonna hold off on this til the weekend. The slackbot code is going to likely require a bit of updating since it hasn't been touched in quite a while.
