### ISSUE TITLE
Shorten line height for course boxes

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#200]
Given the smaller font, the line height should be a little shorter. 

![image](https://user-images.githubusercontent.com/5240018/35537692-28da10d0-0519-11e8-9569-5340bd587618.png)

**Comment by dsifford** [comment]
Just to confirm @michellealiem -- You want the descriptions to be clipped at 20-25 words?

The current clipping number is 30 and for some of the capsules cards, words go right up til the end.

**Comment by dsifford** [comment]
Also: The line height was already adjusted to be reduced from the base line-height for that font size, but I'll adjust this a tad more.

Let's try going from `2em` --> `1.8em`. I think you'll prob like that.

**Comment by michellealiem** [comment]
30 is fine. Let’s see how that plays.
