### ISSUE TITLE
Preset image sizes

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#203]
Can we set preset image sizes to be

**Width:**
Thumbnail 200 px
Medium 400 px
Full 600 px

Currently the thumbnail is sometimes 150 px and sometimes 200 px and sometimes a random number around that, it seems.

Also can we make it so that the THUMBNAIL does not automatically crop the image to a square dimension?

<img width="419" alt="screenshot 2018-01-28 18 05 39" src="https://user-images.githubusercontent.com/15097022/35490652-0a96abe2-0456-11e8-9b0f-bee4e781c49c.png">

**Comment by dsifford** [comment]
This is an option that can be updated in the settings page in wordpress admin. 

https://codex.wordpress.org/Post_Thumbnails#Thumbnail_Sizes

Closing since this isn't a code issue.
