### ISSUE TITLE
Revise access for Editor role

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#292]
Currently only Admin roles can make new user accounts and upload new course content. Can we allow Editors both those abilities, since I anticipate more folks uploading new lessons and courses soon.

**Comment by dsifford** [comment]
What would they need to add new user accounts for?

**Comment by michellealiem** [comment]
When uploading new lessons, the editor may not have written the lessons. They may have been written by new authors. Want to give proper author attribution.
