### ISSUE TITLE
Quiz question double numbering

### ISSUE THREAD

**Issue by jbronner1** [aliemteam/ALiEMU#83]
![image](https://cloud.githubusercontent.com/assets/17776976/21708798/ee9a7140-d3a9-11e6-89b7-cff37aa4484d.png)

Can't figure out LearnDash reason this is happening.

**Comment by dsifford** [comment]
@jbronner1 where is this?

**Comment by dsifford** [comment]
Nevermind. Fixed in 2a668717a636104da38667fc3b655a3f7805ef84.
