### ISSUE TITLE
Rename "Blocks" to "Modules"

### ISSUE THREAD

**Issue by dsifford** [aliemteam/ALiEMU#88]
This is what the consensus was, correct? cc: @michellealiem @jbronner1

**Comment by michellealiem** [comment]
That was my understanding. MODULES it is.

**Comment by jbronner1** [comment]
Agree as above. Question will be how far back to change lingo in blog posts, etc. or do we just move forward from here referring to MODULES? I'm feeling like the latter will be much less tedious

**Comment by dsifford** [comment]
@jbronner1 no blog posts would need to be changed on aliem. Every blog post that exists on aliem has already been using the term "module". They've never switched to using the term "block"
