### ISSUE TITLE
Update AIR Series Design Guideline

### ISSUE THREAD

**Issue by cgaaf** [aliemteam/ALiEMU#93]
AIR Series and AIR Pro should be consistent with out titles are formatted. Ultimately this will be removed on the front end of the website but it matters for removing. New format should be "<Course-Title> (<Year Published>)"

**Comment by dsifford** [comment]
Status on this @Cgaafary?

Can we close this?

**Comment by cgaaf** [comment]
Yes I think we can close it. Seems that the AIR and AIR pro team have been autonomous for a few modules.
